use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use directories::BaseDirs;
use serde::{Deserialize, Serialize};
use tempfile::NamedTempFile;
use uuid::Uuid;

use crate::config::{Config, create_private_directory};

const GENERATED_HEADER: &str = "# Generated by Akeep. Do not edit.\n";

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ScheduleReport {
    pub unit_name: String,
    pub installed: bool,
    pub enabled: bool,
    pub active: bool,
    pub service_path: PathBuf,
    pub timer_path: PathBuf,
}

struct SystemdBackend {
    unit_dir: PathBuf,
    systemctl: PathBuf,
}

pub fn install(config_path: &Path, config: &Config) -> Result<ScheduleReport> {
    let backend = SystemdBackend::for_user()?;
    install_with(config_path, config, &backend)
}

pub fn status(config: &Config) -> Result<ScheduleReport> {
    let backend = SystemdBackend::for_user()?;
    status_with(config.vault.id, &backend)
}

pub fn uninstall(config: &Config) -> Result<ScheduleReport> {
    let backend = SystemdBackend::for_user()?;
    uninstall_with(config.vault.id, &backend)
}

pub fn is_installed(config: &Config) -> Result<bool> {
    let backend = SystemdBackend::for_user()?;
    let (_, service_path, timer_path) = unit_paths(config.vault.id, &backend.unit_dir);
    Ok(service_path.is_file() && timer_path.is_file())
}

fn install_with(
    config_path: &Path,
    config: &Config,
    backend: &SystemdBackend,
) -> Result<ScheduleReport> {
    let executable =
        std::env::current_exe().context("failed to locate the running Akeep executable")?;
    let executable = fs::canonicalize(&executable)
        .with_context(|| format!("failed to resolve executable {}", executable.display()))?;
    let config_path = fs::canonicalize(config_path)
        .with_context(|| format!("failed to resolve configuration {}", config_path.display()))?;
    let (unit_name, service_path, timer_path) = unit_paths(config.vault.id, &backend.unit_dir);
    let service = render_service(&unit_name, &executable, &config_path)?;
    let timer = render_timer(&unit_name);

    create_private_directory(&backend.unit_dir)?;
    let previous_service = read_owned_file(&service_path)?;
    let previous_timer = read_owned_file(&timer_path)?;
    write_atomic(&service_path, service.as_bytes())?;
    if let Err(error) = write_atomic(&timer_path, timer.as_bytes()) {
        restore_file(&service_path, previous_service.as_deref());
        return Err(error);
    }

    let activate: Result<()> = (|| {
        run_systemctl(backend, &["daemon-reload"])?;
        run_systemctl(backend, &["enable", "--now", &unit_name])?;
        Ok(())
    })();
    if let Err(error) = activate {
        restore_file(&service_path, previous_service.as_deref());
        restore_file(&timer_path, previous_timer.as_deref());
        let _ = run_systemctl(backend, &["daemon-reload"]);
        return Err(error)
            .context("failed to activate Akeep schedule; unit files were rolled back");
    }

    status_with(config.vault.id, backend)
}

fn status_with(vault_id: Uuid, backend: &SystemdBackend) -> Result<ScheduleReport> {
    let (unit_name, service_path, timer_path) = unit_paths(vault_id, &backend.unit_dir);
    let installed = service_path.is_file() && timer_path.is_file();
    let (enabled, active) = if installed {
        (
            systemctl_predicate(backend, &["is-enabled", &unit_name])?,
            systemctl_predicate(backend, &["is-active", &unit_name])?,
        )
    } else {
        (false, false)
    };
    Ok(ScheduleReport {
        unit_name,
        installed,
        enabled,
        active,
        service_path,
        timer_path,
    })
}

fn uninstall_with(vault_id: Uuid, backend: &SystemdBackend) -> Result<ScheduleReport> {
    let (unit_name, service_path, timer_path) = unit_paths(vault_id, &backend.unit_dir);
    let previous_service = read_owned_file(&service_path)?;
    let previous_timer = read_owned_file(&timer_path)?;
    if previous_service.is_none() && previous_timer.is_none() {
        return status_with(vault_id, backend);
    }

    let _ = run_systemctl(backend, &["disable", "--now", &unit_name]);
    remove_if_present(&service_path)?;
    remove_if_present(&timer_path)?;
    if let Err(error) = run_systemctl(backend, &["daemon-reload"]) {
        restore_file(&service_path, previous_service.as_deref());
        restore_file(&timer_path, previous_timer.as_deref());
        let _ = run_systemctl(backend, &["daemon-reload"]);
        return Err(error).context("failed to reload systemd; unit files were restored");
    }
    status_with(vault_id, backend)
}

fn render_service(unit_name: &str, executable: &Path, config_path: &Path) -> Result<String> {
    Ok(format!(
        "{GENERATED_HEADER}[Unit]\n\
         Description=Akeep agent-history commit ({unit_name})\n\
         Documentation=https://github.com/eunomia-bpf/akeep\n\
         ConditionPathExists={}\n\n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={} --config {} commit\n\
         Nice=10\n\
         IOSchedulingClass=idle\n\
         IOSchedulingPriority=7\n\
         NoNewPrivileges=true\n\
         PrivateTmp=true\n",
        systemd_unit_path(config_path)?,
        systemd_quote(executable)?,
        systemd_quote(config_path)?,
    ))
}

fn render_timer(unit_name: &str) -> String {
    let service_name = unit_name
        .strip_suffix(".timer")
        .map(|stem| format!("{stem}.service"))
        .unwrap_or_else(|| unit_name.to_string());
    format!(
        "{GENERATED_HEADER}[Unit]\n\
         Description=Weekly Akeep agent-history commit\n\n\
         [Timer]\n\
         OnCalendar=weekly\n\
         Persistent=true\n\
         RandomizedDelaySec=6h\n\
         AccuracySec=1h\n\
         Unit={service_name}\n\n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

fn systemd_quote(path: &Path) -> Result<String> {
    let value = path
        .to_str()
        .with_context(|| format!("systemd path is not UTF-8: {}", path.display()))?;
    let mut quoted = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => quoted.push_str("\\\\"),
            '"' => quoted.push_str("\\\""),
            '%' => quoted.push_str("%%"),
            '$' => quoted.push_str("$$"),
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            '\t' => quoted.push_str("\\t"),
            character if character.is_control() => {
                bail!("unsupported control character in systemd path");
            }
            character => quoted.push(character),
        }
    }
    quoted.push('"');
    Ok(quoted)
}

fn systemd_unit_path(path: &Path) -> Result<String> {
    let bytes = path.as_os_str().as_encoded_bytes();
    if bytes.first() != Some(&b'/') {
        bail!(
            "systemd condition path must be absolute: {}",
            path.display()
        );
    }
    let mut escaped = String::new();
    for byte in bytes {
        match byte {
            b'%' => escaped.push_str("%%"),
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'/' | b'_' | b'-' | b'.' | b'+' | b':' => {
                escaped.push(char::from(*byte))
            }
            byte => escaped.push_str(&format!("\\x{byte:02x}")),
        }
    }
    Ok(escaped)
}

fn unit_paths(vault_id: Uuid, unit_dir: &Path) -> (String, PathBuf, PathBuf) {
    let stem = format!("akeep-{vault_id}");
    let unit_name = format!("{stem}.timer");
    (
        unit_name,
        unit_dir.join(format!("{stem}.service")),
        unit_dir.join(format!("{stem}.timer")),
    )
}

fn read_owned_file(path: &Path) -> Result<Option<Vec<u8>>> {
    match fs::read(path) {
        Ok(contents) => {
            if !contents.starts_with(GENERATED_HEADER.as_bytes()) {
                bail!(
                    "refusing to replace systemd unit not owned by Akeep: {}",
                    path.display()
                );
            }
            Ok(Some(contents))
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => {
            Err(error).with_context(|| format!("failed to inspect systemd unit {}", path.display()))
        }
    }
}

fn write_atomic(path: &Path, contents: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .with_context(|| format!("systemd path {} has no parent", path.display()))?;
    let mut temporary = NamedTempFile::new_in(parent)
        .with_context(|| format!("failed to create temporary unit in {}", parent.display()))?;
    temporary.write_all(contents)?;
    temporary.as_file().sync_all()?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(0o600))?;
    }
    fs::rename(temporary.path(), path)
        .with_context(|| format!("failed to install systemd unit {}", path.display()))?;
    sync_directory(parent)
}

fn restore_file(path: &Path, contents: Option<&[u8]>) {
    match contents {
        Some(contents) => {
            let _ = write_atomic(path, contents);
        }
        None => {
            let _ = fs::remove_file(path);
        }
    }
}

fn remove_if_present(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => {
            Err(error).with_context(|| format!("failed to remove systemd unit {}", path.display()))
        }
    }
}

fn run_systemctl(backend: &SystemdBackend, arguments: &[&str]) -> Result<()> {
    let output = Command::new(&backend.systemctl)
        .arg("--user")
        .args(arguments)
        .output()
        .context("failed to run systemctl --user")?;
    if !output.status.success() {
        bail!(
            "systemctl --user {} failed: {}",
            arguments.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

fn systemctl_predicate(backend: &SystemdBackend, arguments: &[&str]) -> Result<bool> {
    let output = Command::new(&backend.systemctl)
        .arg("--user")
        .args(arguments)
        .output()
        .context("failed to run systemctl --user")?;
    Ok(output.status.success())
}

fn sync_directory(path: &Path) -> Result<()> {
    #[cfg(unix)]
    File::open(path)
        .with_context(|| format!("failed to open directory {}", path.display()))?
        .sync_all()
        .with_context(|| format!("failed to sync directory {}", path.display()))?;
    Ok(())
}

impl SystemdBackend {
    fn for_user() -> Result<Self> {
        if !cfg!(target_os = "linux") {
            bail!("systemd scheduling is currently supported only on Linux");
        }
        let base = BaseDirs::new().context("could not determine user configuration directory")?;
        Ok(Self {
            unit_dir: base.config_dir().join("systemd").join("user"),
            systemctl: PathBuf::from("systemctl"),
        })
    }
}

#[cfg(all(test, unix))]
mod tests {
    use std::os::unix::fs::PermissionsExt;

    use chrono::{DateTime, Utc};
    use tempfile::TempDir;

    use super::*;
    use crate::config::{
        ArchiveConfig, EncryptionConfig, EncryptionMode, SourceOverrides, TargetConfig, VaultConfig,
    };

    #[test]
    fn renders_safe_persistent_weekly_units() {
        let service = render_service(
            "akeep-test.timer",
            Path::new("/opt/Akeep $HOME/%i/akeep"),
            Path::new("/home/user/Akeep \"primary\"/config.toml"),
        )
        .unwrap();
        let timer = render_timer("akeep-test.timer");

        assert!(service.contains("ExecStart=\"/opt/Akeep $$HOME/%%i/akeep\""));
        assert!(service.contains("Akeep \\\"primary\\\""));
        assert!(service.contains("config.toml\" commit\n"));
        assert!(
            service
                .contains("ConditionPathExists=/home/user/Akeep\\x20\\x22primary\\x22/config.toml")
        );
        assert!(service.contains("IOSchedulingClass=idle"));
        assert!(timer.contains("OnCalendar=weekly"));
        assert!(timer.contains("Persistent=true"));
        assert!(timer.contains("RandomizedDelaySec=6h"));
    }

    #[test]
    fn installs_reports_and_uninstalls_with_a_fake_systemctl() {
        let temp = TempDir::new().unwrap();
        let config_path = temp.path().join("config.toml");
        fs::write(&config_path, b"fixture").unwrap();
        let systemctl = temp.path().join("systemctl");
        fs::write(
            &systemctl,
            "#!/bin/sh\ncase \"$*\" in *is-enabled*|*is-active*) exit 0;; *) exit 0;; esac\n",
        )
        .unwrap();
        fs::set_permissions(&systemctl, fs::Permissions::from_mode(0o700)).unwrap();
        let backend = SystemdBackend {
            unit_dir: temp.path().join("units"),
            systemctl,
        };
        let config = sample_config(temp.path());

        let installed = install_with(&config_path, &config, &backend).unwrap();
        assert!(installed.installed);
        assert!(installed.enabled);
        assert!(installed.active);
        assert!(installed.service_path.is_file());
        assert!(installed.timer_path.is_file());

        let removed = uninstall_with(config.vault.id, &backend).unwrap();
        assert!(!removed.installed);
        assert!(!removed.service_path.exists());
        assert!(!removed.timer_path.exists());
    }

    #[test]
    fn refuses_to_replace_a_foreign_unit() {
        let temp = TempDir::new().unwrap();
        let config_path = temp.path().join("config.toml");
        fs::write(&config_path, b"fixture").unwrap();
        let systemctl = temp.path().join("systemctl");
        fs::write(&systemctl, "#!/bin/sh\nexit 0\n").unwrap();
        fs::set_permissions(&systemctl, fs::Permissions::from_mode(0o700)).unwrap();
        let backend = SystemdBackend {
            unit_dir: temp.path().join("units"),
            systemctl,
        };
        fs::create_dir_all(&backend.unit_dir).unwrap();
        let config = sample_config(temp.path());
        let (_, service, _) = unit_paths(config.vault.id, &backend.unit_dir);
        fs::write(&service, b"user-owned unit").unwrap();

        assert!(install_with(&config_path, &config, &backend).is_err());
        assert_eq!(fs::read(service).unwrap(), b"user-owned unit");
    }

    fn sample_config(root: &Path) -> Config {
        Config {
            format_version: 1,
            vault: VaultConfig {
                id: Uuid::nil(),
                created_at: DateTime::<Utc>::from_timestamp(0, 0).unwrap(),
                state_path: root.join("state"),
            },
            target: TargetConfig::Filesystem {
                path: root.join("vault"),
            },
            archive: ArchiveConfig {
                chunk_size: 1024,
                compression_level: 3,
            },
            encryption: EncryptionConfig {
                mode: EncryptionMode::None,
                recipient: None,
                identity_file: None,
            },
            sources: SourceOverrides::default(),
        }
    }
}
